# Generated by Django 5.2.6 on 2026-03-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservedslot',
            unique_together={('class_ref', 'day', 'hour')},
        ),
    ]
