# Generated by Django 5.2.6 on 2026-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_lab_room_subject_semester'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='subject',
                    name='semester_type',
                    field=models.CharField(default='Odd', max_length=4),
                ),
            ],
            database_operations=[],
        ),
    ]
